import type { UserBackup } from "./session";

export function getDemoUserBackup(): UserBackup {
  return {
    version: "11",
    app: "amigo-do-predio",
    exportedAt: "2026-05-29T10:00:00Z",
    profile: {
      nomeCondominio: "Edifício Primavera",
      hasElevador: true,
      hasPiscina: false,
      hasFuncionarios: true,
      hasPortaria: true,
      tipoSindico: "morador",
      numUnidades: 24,
      tipoGestao: "sindico_morador",
      cidade: "São Paulo",
      uf: "SP",
    },
    memoria: {
      administradora: "Administradora Horizonte",
      prestadoraElevador: "Elevadores Confort",
      vencimentoAVCB: "2026-06-13",
      vencimentoSeguro: "2026-08-27",
      fimMandatoSindico: "2026-07-13",
      ultimaAGO: "2025-03-15",
      ultimaDedetizacao: "2026-01-10",
      ultimaLimpezaCaixaDAgua: "2025-09-20",
      ultimaManutencaoElevador: "2026-04-10",
      ultimaInspecaoExtintores: "2025-11-15",
    },
    favorites: [],
    checklists: {},
    pendencias: [
      {
        id: "demo-p1",
        titulo: "Renovar AVCB antes do vencimento (13/06)",
        categoria: "documentos",
        origem: "documento",
        status: "aberta",
        dueDate: "2026-06-10",
        prioridade: "alta",
        createdAt: "2026-05-20T09:00:00Z",
      },
      {
        id: "demo-p2",
        titulo: "Contratar limpeza da caixa d'água (vencida)",
        categoria: "manutencao",
        origem: "manual",
        status: "aberta",
        dueDate: "2026-06-30",
        prioridade: "alta",
        createdAt: "2026-05-10T14:00:00Z",
      },
      {
        id: "demo-p3",
        titulo: "Notificação formal ao morador do ap. 71 (barulho)",
        categoria: "multas",
        origem: "ocorrencia",
        status: "aberta",
        prioridade: "media",
        createdAt: "2026-05-26T11:30:00Z",
      },
    ],
    ocorrencias: [
      {
        id: "demo-o1",
        tipo: "vazamento",
        titulo: "Infiltração — ap. 32B (teto do 31B)",
        descricao: "Morador do 31B relatou infiltração no teto do quarto. Origem apontada: banheiro do 32B.",
        prioridade: "alta",
        statusOcorrencia: "acompanhando",
        proximo: "Acionar vistoria técnica com a administradora",
        createdAt: "2026-05-22T15:30:00Z",
      },
      {
        id: "demo-o2",
        tipo: "barulho",
        titulo: "Reclamação de barulho — ap. 71",
        descricao: "Dois moradores reclamaram de barulho excessivo durante a madrugada nos fins de semana.",
        prioridade: "media",
        statusOcorrencia: "aberta",
        proximo: "Enviar notificação formal ao morador",
        createdAt: "2026-05-26T11:00:00Z",
      },
    ],
    agenda: [
      {
        id: "demo-a1",
        title: "Assembleia Geral Ordinária 2026",
        date: "2026-07-20",
        type: "assembleia",
        note: "Pauta: aprovação de contas e eleição do síndico",
        createdAt: "2026-04-01T09:00:00Z",
      },
      {
        id: "demo-a2",
        title: "Renovação do AVCB",
        date: "2026-06-10",
        type: "vistoria",
        note: "Prazo: 3 dias antes do vencimento em 13/06",
        createdAt: "2026-05-20T09:00:00Z",
      },
    ],
    memoriaAssistida: {
      avcb: {
        value: "2026-06-13",
        precision: "exact",
        status: "filled",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      seguro: {
        value: "2026-08-27",
        precision: "exact",
        status: "filled",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      mandato: {
        value: "2026-07-13",
        precision: "month",
        status: "filled",
        updatedAt: "2026-03-15T10:00:00Z",
      },
    },
    documentos: [
      {
        id: "avcb_clcb",
        status: "tenho",
        dataVencimento: "2026-06-13",
        ondeEsta: "Administradora Horizonte",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "apolice_seguro",
        status: "tenho",
        dataVencimento: "2026-08-27",
        ondeEsta: "Pasta de documentos do condomínio",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "convencao",
        status: "tenho",
        ondeEsta: "Administradora Horizonte (cópia digital)",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "extintores_comprovante",
        status: "tenho",
        dataVencimento: "2026-05-15",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "contrato_elevador",
        status: "tenho",
        observacoes: "Elevadores Confort — contrato mensal",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "caixa_agua_comprovante",
        status: "precisa_localizar",
        updatedAt: "2026-04-01T10:00:00Z",
      },
      {
        id: "ppra_pgr",
        status: "nao_tenho",
        updatedAt: "2026-04-01T10:00:00Z",
      },
      {
        id: "controle_ferias",
        status: "tenho",
        ondeEsta: "Planilha de RH da administradora",
        updatedAt: "2026-03-15T10:00:00Z",
      },
    ],
    funcionarios: [
      {
        id: "demo-f1",
        nomeFuncao: "Carlos Silva",
        cargo: "Porteiro",
        dataAdmissao: "2019-04-01",
        ultimasFeriasGozo: "2025-04-01",
        status: "a_vencer",
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
    ],
    implantacaoMode: "existing",
    manutencoes: [
      {
        id: "demo-m1",
        label: "Manutenção do elevador",
        frequencia: "mensal",
        criticidade: "critica",
        ultimaExecucao: "2026-04-10",
        fornecedor: "Elevadores Confort",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
      {
        id: "demo-m2",
        label: "Inspeção e recarga de extintores",
        frequencia: "semestral",
        criticidade: "critica",
        ultimaExecucao: "2025-11-15",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
      {
        id: "demo-m3",
        label: "Limpeza da caixa d'água",
        frequencia: "semestral",
        criticidade: "critica",
        ultimaExecucao: "2025-09-20",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
      {
        id: "demo-m4",
        label: "Dedetização e controle de pragas",
        frequencia: "semestral",
        criticidade: "importante",
        ultimaExecucao: "2026-01-10",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
    ],
    financialSnapshots: [
      {
        id: "demo-fin-2026-05",
        month: "2026-05",
        estimatedBalance: 18500,
        delinquencyRate: 7,
        liquidityReserve: 12000,
        entries: [
          {
            id: "demo-fin-2026-05-r1",
            type: "receita",
            title: "Cotas condominiais recebidas",
            amount: 42800,
            category: "Receita ordinária",
            status: "previsto",
            createdAt: "2026-05-01T10:00:00Z",
          },
          {
            id: "demo-fin-2026-05-d1",
            type: "despesa",
            title: "Folha e encargos",
            amount: 18600,
            category: "Funcionários",
            status: "previsto",
            createdAt: "2026-05-02T10:00:00Z",
          },
          {
            id: "demo-fin-2026-05-d2",
            type: "despesa",
            title: "Manutenção e contratos",
            amount: 9400,
            category: "Manutenção",
            status: "previsto",
            createdAt: "2026-05-03T10:00:00Z",
          },
        ],
        notes: "Resumo financeiro auxiliar de demonstração.",
        createdAt: "2026-05-31T18:00:00Z",
        updatedAt: "2026-05-31T18:00:00Z",
      },
      {
        id: "demo-fin-2026-06",
        month: "2026-06",
        estimatedBalance: 9800,
        delinquencyRate: 12,
        liquidityReserve: 6400,
        entries: [
          {
            id: "demo-fin-2026-06-r1",
            type: "receita",
            title: "Cotas condominiais recebidas",
            amount: 39200,
            category: "Receita ordinária",
            status: "previsto",
            createdAt: "2026-06-01T10:00:00Z",
          },
          {
            id: "demo-fin-2026-06-d1",
            type: "despesa",
            title: "Folha e encargos",
            amount: 18900,
            category: "Funcionários",
            status: "previsto",
            createdAt: "2026-06-02T10:00:00Z",
          },
          {
            id: "demo-fin-2026-06-d2",
            type: "conta_a_pagar",
            title: "Contrato de elevador",
            amount: 3200,
            dueDate: "2026-06-12",
            category: "Elevadores",
            status: "previsto",
            priority: "alta",
            createdAt: "2026-06-02T10:00:00Z",
          },
          {
            id: "demo-fin-2026-06-d3",
            type: "conta_a_pagar",
            title: "Conta de água",
            amount: 2450,
            dueDate: "2026-06-09",
            category: "Água",
            status: "previsto",
            priority: "media",
            createdAt: "2026-06-03T10:00:00Z",
          },
        ],
        notes: "Inadimplência moderada para demonstrar acompanhamento financeiro operacional.",
        createdAt: "2026-06-06T18:00:00Z",
        updatedAt: "2026-06-06T18:00:00Z",
      },
    ],
    communityPosts: [
      {
        id: "demo-post-1",
        title: "Manutenção preventiva da bomba d'água",
        body: "Haverá manutenção preventiva na bomba d'água em 15/06, das 8h às 12h. A gestão recomenda reservar água para uso essencial durante o período.",
        category: "manutencao",
        visibility: "moradores",
        allowComments: false,
        pinned: true,
        archived: false,
        createdAt: "2026-06-05T09:00:00Z",
        updatedAt: "2026-06-05T09:00:00Z",
      },
      {
        id: "demo-post-2",
        title: "AGO 2026 agendada",
        body: "A Assembleia Geral Ordinária está prevista para 20/07. A pauta será organizada pela gestão e compartilhada previamente pelos canais institucionais.",
        category: "assembleia",
        visibility: "moradores",
        allowComments: false,
        pinned: false,
        archived: false,
        createdAt: "2026-06-02T10:30:00Z",
        updatedAt: "2026-06-02T10:30:00Z",
      },
      {
        id: "demo-post-3",
        title: "Relembrete sobre uso da garagem",
        body: "Para manter a circulação segura, evite deixar objetos nas vagas e áreas de passagem. Situações recorrentes podem ser tratadas pela gestão conforme o regimento interno.",
        category: "regra",
        visibility: "moradores",
        allowComments: true,
        pinned: false,
        archived: false,
        createdAt: "2026-05-31T13:00:00Z",
        updatedAt: "2026-05-31T13:00:00Z",
      },
    ],
    communityComments: [],
    communityRequests: [
      {
        id: "demo-req-1",
        unitNumber: "302",
        authorName: "Morador da 302",
        type: "barulho",
        title: "Barulho recorrente após 22h",
        description: "Registro de ocorrência para acompanhamento pela gestão, sem exposição pública entre moradores.",
        status: "em_analise",
        priority: "alta",
        createdAt: "2026-06-03T20:40:00Z",
        updatedAt: "2026-06-04T09:10:00Z",
      },
      {
        id: "demo-req-2",
        unitNumber: "105",
        authorName: "Morador da 105",
        type: "manutencao",
        title: "Lâmpada queimada no corredor",
        description: "Solicitação registrada pelo canal oficial para troca de lâmpada no 1º andar.",
        status: "resolvido",
        priority: "normal",
        resolutionNote: "Lâmpada substituída pela manutenção em 05/06.",
        createdAt: "2026-06-01T11:20:00Z",
        updatedAt: "2026-06-05T14:00:00Z",
        closedAt: "2026-06-05T14:00:00Z",
      },
    ],
    communityPolls: [
      {
        id: "demo-poll-1",
        title: "Melhor horário para manutenção das áreas comuns",
        description: "Enquete consultiva para reduzir impacto na rotina dos moradores. Não substitui deliberação formal.",
        options: [
          { id: "opt-1", label: "Sábado de manhã" },
          { id: "opt-2", label: "Sábado à tarde" },
          { id: "opt-3", label: "Dia útil pela manhã" },
        ],
        visibility: "moradores",
        status: "ativa",
        endsAt: "2026-06-18",
        createdAt: "2026-06-04T12:00:00Z",
        updatedAt: "2026-06-04T12:00:00Z",
      },
    ],
    communityVotes: [
      { id: "demo-vote-1", pollId: "demo-poll-1", optionId: "opt-1", voterLabel: "101", createdAt: "2026-06-04T13:00:00Z" },
      { id: "demo-vote-2", pollId: "demo-poll-1", optionId: "opt-1", voterLabel: "201", createdAt: "2026-06-04T13:15:00Z" },
      { id: "demo-vote-3", pollId: "demo-poll-1", optionId: "opt-2", voterLabel: "302", createdAt: "2026-06-04T14:10:00Z" },
    ],
    communityDocuments: [
      {
        id: "demo-doc-public-1",
        title: "Convenção do Condomínio",
        category: "convencao",
        description: "Documento de referência para consulta dos condôminos.",
        visibility: "moradores",
        version: "v3",
        publishedAt: "2026-05-30T10:00:00Z",
        createdAt: "2026-05-30T10:00:00Z",
        updatedAt: "2026-05-30T10:00:00Z",
      },
      {
        id: "demo-doc-public-2",
        title: "Ata da AGO 2025",
        category: "ata",
        description: "Registro auxiliar disponibilizado para consulta interna.",
        visibility: "moradores",
        publishedAt: "2026-06-02T10:00:00Z",
        createdAt: "2026-06-02T10:00:00Z",
        updatedAt: "2026-06-02T10:00:00Z",
      },
    ],
    communityTimeline: [
      {
        id: "demo-timeline-1",
        type: "aviso_publicado",
        title: "Aviso publicado: manutenção preventiva da bomba d'água",
        description: "Comunicado disponível no mural oficial.",
        visibility: "moradores",
        sourceModule: "mural",
        sourceId: "demo-post-1",
        relatedPostId: "demo-post-1",
        occurredAt: "2026-06-05T09:00:00Z",
        createdAt: "2026-06-05T09:00:00Z",
      },
      {
        id: "demo-timeline-2",
        type: "solicitacao_resolvida",
        title: "Solicitação resolvida: lâmpada queimada no corredor",
        description: "Registro encerrado pelo canal oficial.",
        visibility: "moradores",
        sourceModule: "requests",
        sourceId: "demo-req-2",
        relatedRequestId: "demo-req-2",
        occurredAt: "2026-06-05T14:00:00Z",
        createdAt: "2026-06-05T14:00:00Z",
      },
      {
        id: "demo-timeline-3",
        type: "enquete_criada",
        title: "Enquete consultiva criada: horário de manutenção",
        description: "Participação organizada para apoiar a gestão.",
        visibility: "moradores",
        sourceModule: "polls",
        sourceId: "demo-poll-1",
        relatedPollId: "demo-poll-1",
        occurredAt: "2026-06-04T12:00:00Z",
        createdAt: "2026-06-04T12:00:00Z",
      },
      {
        id: "demo-timeline-4",
        type: "documento_publicado",
        title: "Documento publicado: Ata da AGO 2025",
        description: "Documento disponibilizado para consulta interna.",
        visibility: "moradores",
        sourceModule: "documents",
        sourceId: "demo-doc-public-2",
        relatedDocumentId: "demo-doc-public-2",
        occurredAt: "2026-06-02T10:00:00Z",
        createdAt: "2026-06-02T10:00:00Z",
      },
    ],
  };
}
