import type { UserBackup } from "./session";

export function getDemoUserBackup(): UserBackup {
  return {
    version: "6",
    app: "amigo-do-predio",
    exportedAt: "2026-05-29T10:00:00Z",
    profile: {
      nomeCondominio: "Edifício Primavera",
      hasElevador: true,
      hasPiscina: false,
      hasFuncionarios: true,
      hasPortaria: true,
      tipoSindico: "morador",
      numUnidades: 24,
      tipoGestao: "sindico_morador",
      cidade: "São Paulo",
      uf: "SP",
    },
    memoria: {
      administradora: "Administradora Horizonte",
      prestadoraElevador: "Elevadores Confort",
      vencimentoAVCB: "2026-06-13",
      vencimentoSeguro: "2026-08-27",
      fimMandatoSindico: "2026-07-13",
      ultimaAGO: "2025-03-15",
      ultimaDedetizacao: "2026-01-10",
      ultimaLimpezaCaixaDAgua: "2025-09-20",
      ultimaManutencaoElevador: "2026-04-10",
      ultimaInspecaoExtintores: "2025-11-15",
    },
    favorites: [],
    checklists: {},
    pendencias: [
      {
        id: "demo-p1",
        titulo: "Renovar AVCB antes do vencimento (13/06)",
        categoria: "documentos",
        origem: "documento",
        status: "aberta",
        dueDate: "2026-06-10",
        prioridade: "alta",
        createdAt: "2026-05-20T09:00:00Z",
      },
      {
        id: "demo-p2",
        titulo: "Contratar limpeza da caixa d'água (vencida)",
        categoria: "manutencao",
        origem: "manual",
        status: "aberta",
        dueDate: "2026-06-30",
        prioridade: "alta",
        createdAt: "2026-05-10T14:00:00Z",
      },
      {
        id: "demo-p3",
        titulo: "Notificação formal ao morador do ap. 71 (barulho)",
        categoria: "multas",
        origem: "ocorrencia",
        status: "aberta",
        prioridade: "media",
        createdAt: "2026-05-26T11:30:00Z",
      },
    ],
    ocorrencias: [
      {
        id: "demo-o1",
        tipo: "vazamento",
        titulo: "Infiltração — ap. 32B (teto do 31B)",
        descricao: "Morador do 31B relatou infiltração no teto do quarto. Origem apontada: banheiro do 32B.",
        prioridade: "alta",
        statusOcorrencia: "acompanhando",
        proximo: "Acionar vistoria técnica com a administradora",
        createdAt: "2026-05-22T15:30:00Z",
      },
      {
        id: "demo-o2",
        tipo: "barulho",
        titulo: "Reclamação de barulho — ap. 71",
        descricao: "Dois moradores reclamaram de barulho excessivo durante a madrugada nos fins de semana.",
        prioridade: "media",
        statusOcorrencia: "aberta",
        proximo: "Enviar notificação formal ao morador",
        createdAt: "2026-05-26T11:00:00Z",
      },
    ],
    agenda: [
      {
        id: "demo-a1",
        title: "Assembleia Geral Ordinária 2026",
        date: "2026-07-20",
        type: "assembleia",
        note: "Pauta: aprovação de contas e eleição do síndico",
        createdAt: "2026-04-01T09:00:00Z",
      },
      {
        id: "demo-a2",
        title: "Renovação do AVCB",
        date: "2026-06-10",
        type: "vistoria",
        note: "Prazo: 3 dias antes do vencimento em 13/06",
        createdAt: "2026-05-20T09:00:00Z",
      },
    ],
    memoriaAssistida: {
      avcb: {
        value: "2026-06-13",
        precision: "exact",
        status: "filled",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      seguro: {
        value: "2026-08-27",
        precision: "exact",
        status: "filled",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      mandato: {
        value: "2026-07-13",
        precision: "month",
        status: "filled",
        updatedAt: "2026-03-15T10:00:00Z",
      },
    },
    documentos: [
      {
        id: "avcb_clcb",
        status: "tenho",
        dataVencimento: "2026-06-13",
        ondeEsta: "Administradora Horizonte",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "apolice_seguro",
        status: "tenho",
        dataVencimento: "2026-08-27",
        ondeEsta: "Pasta de documentos do condomínio",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "convencao",
        status: "tenho",
        ondeEsta: "Administradora Horizonte (cópia digital)",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "extintores_comprovante",
        status: "tenho",
        dataVencimento: "2026-05-15",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "contrato_elevador",
        status: "tenho",
        observacoes: "Elevadores Confort — contrato mensal",
        updatedAt: "2026-03-15T10:00:00Z",
      },
      {
        id: "caixa_agua_comprovante",
        status: "precisa_localizar",
        updatedAt: "2026-04-01T10:00:00Z",
      },
      {
        id: "ppra_pgr",
        status: "nao_tenho",
        updatedAt: "2026-04-01T10:00:00Z",
      },
      {
        id: "controle_ferias",
        status: "tenho",
        ondeEsta: "Planilha de RH da administradora",
        updatedAt: "2026-03-15T10:00:00Z",
      },
    ],
    funcionarios: [
      {
        id: "demo-f1",
        nomeFuncao: "Carlos Silva",
        cargo: "Porteiro",
        dataAdmissao: "2019-04-01",
        ultimasFeriasGozo: "2025-04-01",
        status: "a_vencer",
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
    ],
    implantacaoMode: "existing",
    manutencoes: [
      {
        id: "demo-m1",
        label: "Manutenção do elevador",
        frequencia: "mensal",
        criticidade: "critica",
        ultimaExecucao: "2026-04-10",
        fornecedor: "Elevadores Confort",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
      {
        id: "demo-m2",
        label: "Inspeção e recarga de extintores",
        frequencia: "semestral",
        criticidade: "critica",
        ultimaExecucao: "2025-11-15",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
      {
        id: "demo-m3",
        label: "Limpeza da caixa d'água",
        frequencia: "semestral",
        criticidade: "critica",
        ultimaExecucao: "2025-09-20",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
      {
        id: "demo-m4",
        label: "Dedetização e controle de pragas",
        frequencia: "semestral",
        criticidade: "importante",
        ultimaExecucao: "2026-01-10",
        ativo: true,
        createdAt: "2026-03-01T09:00:00Z",
        updatedAt: "2026-03-01T09:00:00Z",
      },
    ],
  };
}
