import type { UserBackup } from "./session";

// ── Helpers de data (sem dependência externa) ─────────────────────────────────
const BASE = new Date();
BASE.setHours(12, 0, 0, 0);

function addDays(days: number): Date {
  const d = new Date(BASE);
  d.setDate(d.getDate() + days);
  return d;
}

function isoDate(days: number): string {
  return addDays(days).toISOString().slice(0, 10);
}

function isoTs(days: number, time = "T10:00:00Z"): string {
  return isoDate(days) + time;
}

function monthKey(days = 0): string {
  return addDays(days).toISOString().slice(0, 7);
}

// Formata data como "DD/MM" para uso em textos de comunicados
function dmy(days: number): string {
  const d = addDays(days);
  return d.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" });
}

// ─────────────────────────────────────────────────────────────────────────────

export function getDemoUserBackup(): UserBackup {
  return {
    version: "12",
    app: "amigo-do-predio",
    exportedAt: isoTs(-3),
    profile: {
      nomeCondominio: "Edifício Primavera",
      hasElevador: true,
      hasPiscina: false,
      hasFuncionarios: true,
      hasPortaria: true,
      tipoSindico: "morador",
      numUnidades: 24,
      tipoGestao: "sindico_morador",
      cidade: "São Paulo",
      uf: "SP",
    },
    memoria: {
      administradora: "Administradora Horizonte",
      prestadoraElevador: "Elevadores Confort",
      vencimentoAVCB: isoDate(5),
      vencimentoSeguro: isoDate(80),
      fimMandatoSindico: isoDate(35),
      ultimaAGO: isoDate(-450),
      ultimaDedetizacao: isoDate(-150),
      ultimaLimpezaCaixaDAgua: isoDate(-265),
      ultimaManutencaoElevador: isoDate(-60),
      ultimaInspecaoExtintores: isoDate(-200),
    },
    favorites: [],
    checklists: {},
    pendencias: [
      {
        id: "demo-p1",
        titulo: "Renovar AVCB — vence em 5 dias",
        categoria: "documentos",
        origem: "documento",
        status: "aberta",
        dueDate: isoDate(3),
        prioridade: "alta",
        createdAt: isoTs(-18),
      },
      {
        id: "demo-p2",
        titulo: "Contratar limpeza da caixa d'água (vencida)",
        categoria: "manutencao",
        origem: "manual",
        status: "aberta",
        dueDate: isoDate(22),
        prioridade: "alta",
        createdAt: isoTs(-28),
      },
      {
        id: "demo-p3",
        titulo: "Notificação formal ao morador do ap. 71 (barulho)",
        categoria: "multas",
        origem: "ocorrencia",
        status: "aberta",
        prioridade: "media",
        createdAt: isoTs(-12),
      },
    ],
    ocorrencias: [
      {
        id: "demo-o1",
        tipo: "vazamento",
        titulo: "Infiltração — ap. 32B (teto do 31B)",
        descricao: "Morador do 31B relatou infiltração no teto do quarto. Origem apontada: banheiro do 32B.",
        prioridade: "alta",
        statusOcorrencia: "acompanhando",
        proximo: "Acionar vistoria técnica com a administradora",
        createdAt: isoTs(-16),
      },
      {
        id: "demo-o2",
        tipo: "barulho",
        titulo: "Reclamação de barulho — ap. 71",
        descricao: "Dois moradores reclamaram de barulho excessivo durante a madrugada nos fins de semana.",
        prioridade: "media",
        statusOcorrencia: "aberta",
        proximo: "Enviar notificação formal ao morador",
        createdAt: isoTs(-12),
      },
    ],
    agenda: [
      {
        id: "demo-a1",
        title: "Assembleia Geral Ordinária",
        date: isoDate(42),
        type: "assembleia",
        note: "Pauta: aprovação de contas e eleição do síndico",
        createdAt: isoTs(-60),
      },
      {
        id: "demo-a2",
        title: "Renovação do AVCB",
        date: isoDate(2),
        type: "vistoria",
        note: "Prazo: 3 dias antes do vencimento do AVCB",
        createdAt: isoTs(-18),
      },
    ],
    memoriaAssistida: {
      avcb: {
        value: isoDate(5),
        precision: "exact",
        status: "filled",
        updatedAt: isoTs(-90),
      },
      seguro: {
        value: isoDate(80),
        precision: "exact",
        status: "filled",
        updatedAt: isoTs(-90),
      },
      mandato: {
        value: isoDate(35),
        precision: "month",
        status: "filled",
        updatedAt: isoTs(-90),
      },
    },
    documentos: [
      {
        id: "avcb_clcb",
        status: "tenho",
        dataVencimento: isoDate(5),
        ondeEsta: "Administradora Horizonte",
        updatedAt: isoTs(-90),
      },
      {
        id: "apolice_seguro",
        status: "tenho",
        dataVencimento: isoDate(80),
        ondeEsta: "Pasta de documentos do condomínio",
        updatedAt: isoTs(-90),
      },
      {
        id: "convencao",
        status: "tenho",
        ondeEsta: "Administradora Horizonte (cópia digital)",
        updatedAt: isoTs(-90),
      },
      {
        id: "extintores_comprovante",
        status: "tenho",
        dataVencimento: isoDate(-23),
        updatedAt: isoTs(-90),
      },
      {
        id: "contrato_elevador",
        status: "tenho",
        observacoes: "Elevadores Confort — contrato mensal",
        updatedAt: isoTs(-90),
      },
      {
        id: "caixa_agua_comprovante",
        status: "precisa_localizar",
        updatedAt: isoTs(-60),
      },
      {
        id: "ppra_pgr",
        status: "nao_tenho",
        updatedAt: isoTs(-60),
      },
      {
        id: "controle_ferias",
        status: "tenho",
        ondeEsta: "Planilha de RH da administradora",
        updatedAt: isoTs(-90),
      },
    ],
    funcionarios: [
      {
        id: "demo-f1",
        nomeFuncao: "Carlos Silva",
        cargo: "Porteiro",
        dataAdmissao: "2019-04-01",
        ultimasFeriasGozo: isoDate(-425),
        status: "a_vencer",
        createdAt: isoTs(-100),
        updatedAt: isoTs(-100),
      },
    ],
    implantacaoMode: "existing",
    manutencoes: [
      {
        id: "demo-m1",
        label: "Manutenção do elevador",
        frequencia: "mensal",
        criticidade: "critica",
        ultimaExecucao: isoDate(-60),
        fornecedor: "Elevadores Confort",
        ativo: true,
        createdAt: isoTs(-100),
        updatedAt: isoTs(-100),
      },
      {
        id: "demo-m2",
        label: "Inspeção e recarga de extintores",
        frequencia: "semestral",
        criticidade: "critica",
        ultimaExecucao: isoDate(-200),
        ativo: true,
        createdAt: isoTs(-100),
        updatedAt: isoTs(-100),
      },
      {
        id: "demo-m3",
        label: "Limpeza da caixa d'água",
        frequencia: "semestral",
        criticidade: "critica",
        ultimaExecucao: isoDate(-265),
        ativo: true,
        createdAt: isoTs(-100),
        updatedAt: isoTs(-100),
      },
      {
        id: "demo-m4",
        label: "Dedetização e controle de pragas",
        frequencia: "semestral",
        criticidade: "importante",
        ultimaExecucao: isoDate(-150),
        ativo: true,
        createdAt: isoTs(-100),
        updatedAt: isoTs(-100),
      },
    ],
    financialSnapshots: [
      {
        id: `demo-fin-${monthKey(-35)}`,
        month: monthKey(-35),
        estimatedBalance: 18500,
        delinquencyRate: 7,
        liquidityReserve: 12000,
        entries: [
          {
            id: `demo-fin-${monthKey(-35)}-r1`,
            type: "receita",
            title: "Cotas condominiais recebidas",
            amount: 42800,
            category: "Receita ordinária",
            status: "previsto",
            createdAt: isoTs(-35) + "",
          },
          {
            id: `demo-fin-${monthKey(-35)}-d1`,
            type: "despesa",
            title: "Folha e encargos",
            amount: 18600,
            category: "Funcionários",
            status: "previsto",
            createdAt: isoTs(-34),
          },
          {
            id: `demo-fin-${monthKey(-35)}-d2`,
            type: "despesa",
            title: "Manutenção e contratos",
            amount: 9400,
            category: "Manutenção",
            status: "previsto",
            createdAt: isoTs(-33),
          },
        ],
        notes: "Resumo financeiro auxiliar de demonstração.",
        createdAt: isoTs(-32),
        updatedAt: isoTs(-32),
      },
      {
        id: `demo-fin-${monthKey()}`,
        month: monthKey(),
        estimatedBalance: 9800,
        delinquencyRate: 12,
        liquidityReserve: 6400,
        entries: [
          {
            id: `demo-fin-${monthKey()}-r1`,
            type: "receita",
            title: "Cotas condominiais recebidas",
            amount: 39200,
            category: "Receita ordinária",
            status: "previsto",
            createdAt: isoTs(-6),
          },
          {
            id: `demo-fin-${monthKey()}-d1`,
            type: "despesa",
            title: "Folha e encargos",
            amount: 18900,
            category: "Funcionários",
            status: "previsto",
            createdAt: isoTs(-5),
          },
          {
            id: `demo-fin-${monthKey()}-d2`,
            type: "conta_a_pagar",
            title: "Contrato de elevador",
            amount: 3200,
            dueDate: isoDate(4),
            category: "Elevadores",
            status: "previsto",
            priority: "alta",
            createdAt: isoTs(-5),
          },
          {
            id: `demo-fin-${monthKey()}-d3`,
            type: "conta_a_pagar",
            title: "Conta de água",
            amount: 2450,
            dueDate: isoDate(1),
            category: "Água",
            status: "previsto",
            priority: "media",
            createdAt: isoTs(-4),
          },
        ],
        notes: "Inadimplência moderada para demonstrar acompanhamento financeiro operacional.",
        createdAt: isoTs(-2),
        updatedAt: isoTs(-2),
      },
    ],
    communityPosts: [
      {
        id: "demo-post-1",
        title: "Manutenção preventiva da bomba d'água",
        body: `Haverá manutenção preventiva na bomba d'água em ${dmy(10)}, das 8h às 12h. A gestão recomenda reservar água para uso essencial durante o período.`,
        category: "manutencao",
        visibility: "moradores",
        allowComments: false,
        pinned: true,
        archived: false,
        createdAt: isoTs(-3),
        updatedAt: isoTs(-3),
      },
      {
        id: "demo-post-2",
        title: "Assembleia Geral Ordinária agendada",
        body: `A Assembleia Geral Ordinária está prevista para ${dmy(42)}. A pauta será organizada pela gestão e compartilhada previamente pelos canais institucionais.`,
        category: "assembleia",
        visibility: "moradores",
        allowComments: false,
        pinned: false,
        archived: false,
        createdAt: isoTs(-7),
        updatedAt: isoTs(-7),
      },
      {
        id: "demo-post-3",
        title: "Relembrete sobre uso da garagem",
        body: "Para manter a circulação segura, evite deixar objetos nas vagas e áreas de passagem. Situações recorrentes podem ser tratadas pela gestão conforme o regimento interno.",
        category: "regra",
        visibility: "moradores",
        allowComments: true,
        pinned: false,
        archived: false,
        createdAt: isoTs(-8),
        updatedAt: isoTs(-8),
      },
    ],
    communityComments: [],
    communityRequests: [
      {
        id: "demo-req-1",
        unitNumber: "302",
        authorName: "Morador da 302",
        type: "barulho",
        title: "Barulho recorrente após 22h",
        description: "Registro de ocorrência para acompanhamento pela gestão, sem exposição pública entre moradores.",
        status: "em_analise",
        priority: "alta",
        createdAt: isoTs(-5, "T20:40:00Z"),
        updatedAt: isoTs(-4, "T09:10:00Z"),
      },
      {
        id: "demo-req-2",
        unitNumber: "105",
        authorName: "Morador da 105",
        type: "manutencao",
        title: "Lâmpada queimada no corredor",
        description: "Solicitação registrada pelo canal oficial para troca de lâmpada no 1º andar.",
        status: "resolvido",
        priority: "normal",
        resolutionNote: "Lâmpada substituída pela equipe de manutenção.",
        createdAt: isoTs(-7, "T11:20:00Z"),
        updatedAt: isoTs(-3, "T14:00:00Z"),
        closedAt: isoTs(-3, "T14:00:00Z"),
      },
    ],
    communityPolls: [
      {
        id: "demo-poll-1",
        title: "Melhor horário para manutenção das áreas comuns",
        description: "Enquete consultiva para reduzir impacto na rotina dos moradores. Não substitui deliberação formal.",
        options: [
          { id: "opt-1", label: "Sábado de manhã" },
          { id: "opt-2", label: "Sábado à tarde" },
          { id: "opt-3", label: "Dia útil pela manhã" },
        ],
        visibility: "moradores",
        status: "ativa",
        endsAt: isoDate(10),
        createdAt: isoTs(-4),
        updatedAt: isoTs(-4),
      },
    ],
    communityVotes: [
      { id: "demo-vote-1", pollId: "demo-poll-1", optionId: "opt-1", voterLabel: "101", createdAt: isoTs(-4, "T13:00:00Z") },
      { id: "demo-vote-2", pollId: "demo-poll-1", optionId: "opt-1", voterLabel: "201", createdAt: isoTs(-4, "T13:15:00Z") },
      { id: "demo-vote-3", pollId: "demo-poll-1", optionId: "opt-2", voterLabel: "302", createdAt: isoTs(-4, "T14:10:00Z") },
    ],
    communityDocuments: [
      {
        id: "demo-doc-public-1",
        title: "Convenção do Condomínio",
        category: "convencao",
        description: "Documento de referência para consulta dos condôminos.",
        visibility: "moradores",
        version: "v3",
        publishedAt: isoTs(-9),
        createdAt: isoTs(-9),
        updatedAt: isoTs(-9),
      },
      {
        id: "demo-doc-public-2",
        title: "Ata da última AGO",
        category: "ata",
        description: "Registro auxiliar disponibilizado para consulta interna.",
        visibility: "moradores",
        publishedAt: isoTs(-7),
        createdAt: isoTs(-7),
        updatedAt: isoTs(-7),
      },
    ],
    decisions: [
      {
        id: "demo-dec-1",
        title: "Contratar limpeza da caixa d'água",
        date: isoDate(-30),
        category: "manutencao",
        context: "Última limpeza foi há mais de 8 meses, acima do prazo recomendado pela ABNT.",
        rationale: "Obrigação sanitária e de saúde pública do condomínio.",
        outcome: "Aprovada contratação de empresa especializada por R$ 1.400.",
        status: "em_execucao",
        riskLevel: "medio",
        nextStep: "Agendar serviço em data de menor impacto para moradores",
        createdAt: isoTs(-30),
        updatedAt: isoTs(-30),
      },
      {
        id: "demo-dec-2",
        title: "Renovar AVCB junto ao Corpo de Bombeiros",
        date: isoDate(-10),
        category: "seguranca",
        context: "Vencimento do AVCB em 5 dias.",
        rationale: "Documento obrigatório com prazo crítico — multa e risco legal em caso de omissão.",
        outcome: "Providenciar renovação com empresa habilitada para vistoria.",
        status: "registrada",
        riskLevel: "alto",
        nextStep: "Acionar empresa responsável para agendar vistoria técnica",
        createdAt: isoTs(-10),
        updatedAt: isoTs(-10),
      },
      {
        id: "demo-dec-3",
        title: "Aprovação de dedetização preventiva",
        date: isoDate(-55),
        category: "manutencao",
        context: "Moradores relataram presença de insetos em áreas comuns.",
        rationale: "Manutenção preventiva obrigatória para áreas comuns.",
        outcome: "Aprovado orçamento de R$ 1.200 com empresa cadastrada.",
        status: "concluida",
        riskLevel: "baixo",
        createdAt: isoTs(-55),
        updatedAt: isoTs(-40),
      },
    ],
    suppliers: [
      {
        id: "demo-sup-1",
        name: "Elevadores Confort",
        category: "elevador",
        contact: "(11) 99800-1234",
        responsible: "Sr. Marcos",
        active: true,
        monthlyAmount: 3200,
        serviceHistory: [
          {
            id: "demo-svc-1",
            date: isoDate(-32),
            description: "Manutenção preventiva mensal — cabine e sistema de freios.",
            createdAt: isoTs(-32),
          },
        ],
        rating: 4,
        createdAt: isoTs(-180),
        updatedAt: isoTs(-32),
      },
      {
        id: "demo-sup-2",
        name: "Administradora Horizonte",
        category: "administradora",
        contact: "(11) 3456-7890",
        responsible: "Dra. Ana Luísa",
        active: true,
        serviceHistory: [],
        createdAt: isoTs(-365),
        updatedAt: isoTs(-30),
      },
      {
        id: "demo-sup-3",
        name: "Limpeza Total",
        category: "limpeza",
        contact: "(11) 98765-4321",
        active: true,
        monthlyAmount: 2800,
        serviceHistory: [],
        rating: 3,
        createdAt: isoTs(-120),
        updatedAt: isoTs(-7),
      },
    ],
    unitEvents: [
      {
        id: "demo-ue-1",
        unit: "302",
        type: "reclamacao",
        date: isoDate(-5),
        title: "Barulho recorrente após 22h",
        description: "Dois moradores reportaram barulho excessivo originado da unidade 302 nos fins de semana.",
        status: "aberto",
        createdAt: isoTs(-5),
      },
      {
        id: "demo-ue-2",
        unit: "71",
        type: "advertencia",
        date: isoDate(-12),
        title: "Advertência por descumprimento de horário",
        description: "Primeira notificação formal por barulho após 22h, conforme regimento interno.",
        status: "aberto",
        createdAt: isoTs(-12),
      },
      {
        id: "demo-ue-3",
        unit: "105",
        type: "ocorrencia",
        date: isoDate(-7),
        title: "Solicitação de manutenção encerrada",
        description: "Lâmpada queimada no corredor do 1º andar substituída pela equipe de manutenção.",
        status: "resolvido",
        resolvedAt: isoDate(-3),
        createdAt: isoTs(-7),
      },
    ],
    communityReservations: [
      {
        id: "demo-res-1",
        unit: "201",
        requesterName: "Morador da 201",
        space: "Salão de Festas",
        date: isoDate(14),
        timeStart: "14:00",
        timeEnd: "22:00",
        description: "Aniversário — mesa para 30 pessoas.",
        status: "aprovada",
        approvedBy: "Síndico",
        createdAt: isoTs(-3),
        updatedAt: isoTs(-1),
      },
      {
        id: "demo-res-2",
        unit: "504",
        requesterName: "Morador da 504",
        space: "Churrasqueira",
        date: isoDate(7),
        timeStart: "12:00",
        timeEnd: "18:00",
        description: "Confraternização familiar.",
        status: "solicitada",
        createdAt: isoTs(-1),
        updatedAt: isoTs(-1),
      },
      {
        id: "demo-res-3",
        unit: "101",
        requesterName: "Morador da 101",
        space: "Salão de Festas",
        date: isoDate(-7),
        timeStart: "18:00",
        timeEnd: "23:00",
        description: "Jantar de confraternização.",
        status: "cancelada",
        createdAt: isoTs(-14),
        updatedAt: isoTs(-8),
      },
    ],
    communityTimeline: [
      {
        id: "demo-timeline-1",
        type: "aviso_publicado",
        title: "Aviso publicado: manutenção preventiva da bomba d'água",
        description: "Comunicado disponível no mural oficial.",
        visibility: "moradores",
        sourceModule: "mural",
        sourceId: "demo-post-1",
        relatedPostId: "demo-post-1",
        occurredAt: isoTs(-3),
        createdAt: isoTs(-3),
      },
      {
        id: "demo-timeline-2",
        type: "solicitacao_resolvida",
        title: "Solicitação resolvida: lâmpada queimada no corredor",
        description: "Registro encerrado pelo canal oficial.",
        visibility: "moradores",
        sourceModule: "requests",
        sourceId: "demo-req-2",
        relatedRequestId: "demo-req-2",
        occurredAt: isoTs(-3, "T14:00:00Z"),
        createdAt: isoTs(-3, "T14:00:00Z"),
      },
      {
        id: "demo-timeline-3",
        type: "enquete_criada",
        title: "Enquete consultiva criada: horário de manutenção",
        description: "Participação organizada para apoiar a gestão.",
        visibility: "moradores",
        sourceModule: "polls",
        sourceId: "demo-poll-1",
        relatedPollId: "demo-poll-1",
        occurredAt: isoTs(-4),
        createdAt: isoTs(-4),
      },
      {
        id: "demo-timeline-4",
        type: "documento_publicado",
        title: "Documento publicado: Ata da última AGO",
        description: "Documento disponibilizado para consulta interna.",
        visibility: "moradores",
        sourceModule: "documents",
        sourceId: "demo-doc-public-2",
        relatedDocumentId: "demo-doc-public-2",
        occurredAt: isoTs(-7),
        createdAt: isoTs(-7),
      },
    ],
  };
}
